version: "3.7"
services:
  fr24feed-piaware:
    image: "thomx/fr24feed-piaware"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro # needed to sync time for MLAT
    environment: 
      - "FR24FEED_FR24KEY=MY_SHARING_KEY"
      - "PIAWARE_FEEDER_DASH_ID=MY_FEEDER_ID"
      - "HTML_SITE_LAT=MY_SITE_LAT"
      - "HTML_SITE_LON=MY_SITE_LON"
      - "HTML_SITE_NAME=MY_SITE_NAME"
      - "HTML_DEFAULT_TRACKER=Flightradar24"
      - "HTML_RECEIVER_STATS_PAGE_FLIGHTAWARE=https://flightaware.com/adsb/stats/user/"
      - "HTML_RECEIVER_STATS_PAGE_FLIGHTRADAR24=https://www.flightradar24.com/account/feed-stats/?id=<YOUR_RECEIVERS_ID>"
      - "HTML_FR24_FEEDER_STATUS_PAGE=http://<dockerhost>:8754/"
      - "PANORAMA_ID=MY_PANORAMA_ID"
    devices:
      - "/dev/bus/usb"
    # ports
    # 8754 - DUMP1090 server port
    # 8080 - HTTP server port
    ports:
      - "8754:8754"
      - "8080:8080"
    logging:
      options:
        max-size: "30m"
